apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "isoboot.fullname" . }}-manager-role
  labels:
    {{- include "isoboot.labels" . | nindent 4 }}
rules:
- apiGroups:
  - boot.isoboot.github.io
  resources:
  - networkboots
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - boot.isoboot.github.io
  resources:
  - networkboots/finalizers
  verbs:
  - update
- apiGroups:
  - boot.isoboot.github.io
  resources:
  - networkboots/status
  verbs:
  - get
  - patch
  - update
