apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "isoboot.fullname" . }}-leader-election-rolebinding
  labels:
    {{- include "isoboot.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "isoboot.fullname" . }}-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ include "isoboot.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
