apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "isoboot.fullname" . }}-controller-manager
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "isoboot.labels" . | nindent 4 }}
