apiVersion: v2
name: isoboot
description: A Kubernetes controller for network boot orchestration (PXE/iPXE)
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - pxe
  - ipxe
  - netboot
  - kubernetes
  - controller
home: https://github.com/isoboot/isoboot
sources:
  - https://github.com/isoboot/isoboot
maintainers:
  - name: isoboot
    url: https://github.com/isoboot
