# This rule is not used by the project isoboot itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over boot.isoboot.github.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: isoboot
    app.kubernetes.io/managed-by: kustomize
  name: networkboot-admin-role
rules:
- apiGroups:
  - boot.isoboot.github.io
  resources:
  - networkboots
  verbs:
  - '*'
- apiGroups:
  - boot.isoboot.github.io
  resources:
  - networkboots/status
  verbs:
  - get
