apiVersion: isoboot.github.io/v1alpha1
kind: BootSource
metadata:
  labels:
    app.kubernetes.io/name: isoboot
    app.kubernetes.io/managed-by: kustomize
  name: debian-trixie-netboot
spec:
  kernel:
    url:
      binary: "https://deb.debian.org/debian/dists/trixie/main/installer-amd64/current/images/netboot/debian-installer/amd64/linux"
      shasum: "https://deb.debian.org/debian/dists/trixie/main/installer-amd64/current/images/SHA256SUMS"
  initrd:
    url:
      binary: "https://deb.debian.org/debian/dists/trixie/main/installer-amd64/current/images/netboot/debian-installer/amd64/initrd.gz"
      shasum: "https://deb.debian.org/debian/dists/trixie/main/installer-amd64/current/images/SHA256SUMS"
  firmware:
    url:
      binary: "https://cdimage.debian.org/cdimage/firmware/trixie/13.3.0/firmware.cpio.gz"
      shasum: "https://cdimage.debian.org/cdimage/firmware/trixie/13.3.0/SHA256SUMS"
